"""Discord Bot presentation interface managing command routing and notification dispatches."""

from typing import Any

from yukinoaaa.application.backtest.orchestrator import BacktestOrchestrator
from yukinoaaa.application.interfaces.logger import ILogger
from yukinoaaa.application.interfaces.notification import INotificationService
from yukinoaaa.application.trading.portfolio_service import PortfolioService
from yukinoaaa.presentation.discord.commands import DiscordCommandRouter


class DiscordBot:
    """Presentation layer Discord Bot interface handling slash commands and alerts without external SDKs."""

    def __init__(
        self,
        notification_service: INotificationService,
        logger: ILogger,
        portfolio_service: PortfolioService | None = None,
        orchestrator: BacktestOrchestrator | None = None,
    ) -> None:
        """Initialize Discord bot with notification adapter and command router."""
        self._notifier = notification_service
        self._logger = logger.bind(module="DiscordBot")
        self._router = DiscordCommandRouter(
            logger=logger,
            portfolio_service=portfolio_service,
            orchestrator=orchestrator,
        )
        self._is_running = False

    async def start(self) -> None:
        """Start Discord bot interface."""
        if self._is_running:
            return
        await self._notifier.start()
        self._is_running = True
        self._logger.info("Discord Bot presentation interface initialized and listening")

    async def stop(self) -> None:
        """Stop Discord bot interface."""
        if not self._is_running:
            return
        await self._notifier.stop()
        self._is_running = False
        self._logger.info("Discord Bot interface shut down")

    async def handle_message(
        self, message_content: str, user_id: str = "default_user"
    ) -> dict[str, Any]:
        """Process incoming chat message or interaction and dispatch response embed.

        Args:
            message_content: Raw message text, e.g. '/portfolio'.
            user_id: Discord User ID.

        Returns:
            Embed response dictionary generated by command execution.
        """
        if not self._is_running:
            self._logger.warning("Message received while DiscordBot is stopped", user_id=user_id)
            return {"title": "Error", "description": "Bot is currently offline.", "color": 0xE74C3C}

        self._logger.debug(
            "Processing Discord message interaction", content=message_content, user_id=user_id
        )
        embed_response = await self._router.execute_command(message_content, user_id)

        # Dispatch response back via notification adapter
        await self._notifier.send_embed(
            title=str(embed_response.get("title", "Response")),
            description=str(embed_response.get("description", "")),
            color=int(embed_response.get("color", 0x3498DB)),
            fields=embed_response.get("fields"),
            footer=embed_response.get("footer", {}).get("text")
            if isinstance(embed_response.get("footer"), dict)
            else None,
        )
        return embed_response
